version: '3'
services:
  api:
    build: ./api
    depends_on:
      - db
    environment:
      BUNDLE_PATH: /usr/local/bundle
      RAILS_ENV: 'development'
      TZ: Asia/Tokyo
    ports:
      - '3040:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./api:/root/api
      - bundle:/usr/local/bundle
  db:
    image: postgres:11
    volumes:
      - data:/var/lib/postgresql/data
  front:
    build: ./front
    ports:
      - '8000:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./front:/root/front
      - node_modules:/root/front/node_modules
volumes:
  bundle:
    driver: local
  data:
    driver: local
  node_modules:
    driver: local
